# Generated by Django 4.2.1 on 2023-06-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myimagemodel',
            name='file_name',
            field=models.ImageField(upload_to=''),
        ),
    ]
