# Generated by Django 4.2.1 on 2023-06-10 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_alter_myimagemodel_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myimagemodel',
            name='file_name',
        ),
    ]
